FROM bfren/alpine-s6:alpine<%= ${ALPINE_MINOR} %>-<%= ${BASE_REVISION} %>

LABEL org.opencontainers.image.source="https://github.com/bfren/docker-apache"

ARG BF_IMAGE
ARG BF_VERSION

EXPOSE 80

COPY ./overlay /
COPY ./<%= ${APACHE_MINOR} %>/overlay /

RUN bf-install

VOLUME [ "/www" ]
