FROM bfren/alpine-s6:alpine<%= ${ALPINE_MINOR} %>-<%= ${BASE_REVISION} %>

ARG BF_IMAGE
ARG BF_VERSION

EXPOSE 80

COPY ./overlay /
COPY ./<%= ${APACHE_MINOR} %>/overlay /

RUN bf-install

VOLUME [ "/www" ]
