#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Add environment variables.
#======================================================================================================================

bf-env "APACHE_LIB" "${BF_LIB}/apache"

APACHE_WWW=/www
bf-env "APACHE_WWW" "${APACHE_WWW}"
bf-env "APACHE_DOCROOT" "${APACHE_WWW}/htdocs"
bf-env "APACHE_CONF" "/etc/apache2/httpd.conf"
bf-env "APACHE_HELPERS" "/etc/apache2/helpers"
bf-env "APACHE_MODULES" "/etc/apache2/modules"
bf-env "APACHE_LOCALHOST_CONF" "/etc/apache2/sites/localhost.conf"

APACHE_RUN_DIR=/run/httpd
bf-env "APACHE_RUN_DIR" "${APACHE_RUN_DIR}"
bf-env "APACHE_PID_FILE" "${APACHE_RUN_DIR}/httpd.pid"
