#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Generate configuration files.
#======================================================================================================================

bf-echo "Generating Apache configuration files..."
HTTPD_CONF=httpd.conf
bf-debug " .. ${HTTPD_CONF}"
bf-esh ${BF_TEMPLATES}/${HTTPD_CONF}.esh ${APACHE_CONF}
