#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# If /www/htdocs already exists, migration to v3 has been done.
#======================================================================================================================

HTDOCS=/www/htdocs
if [ -d ${HTDOCS} ] ; then
    bf-echo "${HTDOCS} already exists."
    exit 0
fi


#======================================================================================================================
# If nothing exists in /www, simply create /www/htdocs.
#======================================================================================================================

if [ "$(ls /www)" = "" ] ; then
    bf-echo "Creating ${HTDOCS}."
    mkdir ${HTDOCS}
    exit 0
fi


#======================================================================================================================
# Move /www files to a temporary directory, then to /www/htdocs and reapply permissions.
#======================================================================================================================

bf-echo "Moving /www/* to ${HTDOCS}..."

bf-debug " .. create temporary directory..."
TMP_DIR=`mktemp -d -t apache.XXXXXX`

bf-debug " .. moving /www/* to ${TMP_DIR}..."
mv /www/* ${TMP_DIR}/

bf-debug " .. moving ${TMP_DIR} to ${HTDOCS}..."
mv ${TMP_DIR} ${HTDOCS}

bf-debug " .. reapplying permissions"
bf-ch-apply "${BF_CH_D}/11-apache-www"

bf-done
