#!/usr/bin/with-contenv sh

set -euo pipefail


#======================================================================================================================
# Ensure Apache is closed gracefully and use base executable to terminate all services.
#======================================================================================================================

NAME=${PWD##*/}
bf-debug "Quitting Apache." "${NAME}/$(basename ${0})"
apachectl graceful-stop

bf-svc-finish -s ${NAME} -t
