#!/usr/bin/with-contenv sh

set -euo pipefail
export BF_E="${PWD##*/}/$(basename ${0})"


#======================================================================================================================
# Start Apache as a foreground service.
#======================================================================================================================

bf-echo "Starting Apache in foreground mode."
httpd -D FOREGROUND
