#!/command/with-contenv sh

set -euo pipefail
export BF_E="${PWD##*/}/$(basename ${0})"


#======================================================================================================================
# Start Apache as a foreground service, if it isn't already running.
#======================================================================================================================

if [ -z "$(pidof httpd)" ] ; then

    bf-echo "Starting Apache in foreground mode."
    apachectl -k start -D FOREGROUND

    bf-env "BF_APACHE_RESTARTING" "0"

else

    bf-debug "Apache already running."

fi
