name: publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        alpine: [ "3.8", "3.10", "3.13", "3.14", "3.15", "3.16", "3.17", "edge" ]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Get repository name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash
      -
        name: Read image version
        uses: bfren/read-file@v2
        with:
          file: ./VERSION_MAJOR
        id: version_major
      -
        name: Read image version
        uses: bfren/read-file@v2
        with:
          file: ./VERSION_MINOR
        id: version_minor
      -
        name: Read image version
        uses: bfren/read-file@v2
        with:
          file: ./VERSION
        id: version
      -
        name: Read Apache version - revision
        uses: bfren/read-file@v2
        with:
          file: ./alpine${{ matrix.alpine }}/overlay/tmp/APACHE_REVISION
        id: apache_revision
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./alpine${{ matrix.alpine }}/Dockerfile
          build-args: |
            BF_IMAGE=${{ env.REPOSITORY_NAME }}
            BF_VERSION=${{ steps.version.outputs.contents }}
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bfren/apache:apache${{ steps.apache_revision.outputs.contents }}-alpine${{ matrix.alpine }}
            bfren/apache:apache${{ steps.apache_revision.outputs.contents }}-alpine${{ matrix.alpine }}-${{ steps.version_major.outputs.contents }}
            bfren/apache:apache${{ steps.apache_revision.outputs.contents }}-alpine${{ matrix.alpine }}-${{ steps.version_minor.outputs.contents }}
            bfren/apache:apache${{ steps.apache_revision.outputs.contents }}-alpine${{ matrix.alpine }}-${{ steps.version.outputs.contents }}
      -
        name: Build and push default (all Apache versions)
        id: docker_build_default_all
        if: matrix.alpine == '3.10' || matrix.alpine == '3.17'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./alpine${{ matrix.alpine }}/Dockerfile
          build-args: |
            BF_IMAGE=${{ env.REPOSITORY_NAME }}
            BF_VERSION=${{ steps.version.outputs.contents }}
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bfren/apache:apache${{ steps.apache_revision.outputs.contents }}
            bfren/apache:apache${{ steps.apache_revision.outputs.contents }}-${{ steps.version_major.outputs.contents }}
            bfren/apache:apache${{ steps.apache_revision.outputs.contents }}-${{ steps.version_minor.outputs.contents }}
            bfren/apache:apache${{ steps.apache_revision.outputs.contents }}-${{ steps.version.outputs.contents }}
      -
        name: Build and push default
        id: docker_build_default
        if: matrix.alpine == '3.17'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./alpine${{ matrix.alpine }}/Dockerfile
          build-args: |
            BF_IMAGE=${{ env.REPOSITORY_NAME }}
            BF_VERSION=${{ steps.version.outputs.contents }}
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bfren/apache:latest
            bfren/apache:${{ steps.version_major.outputs.contents }}
            bfren/apache:${{ steps.version_minor.outputs.contents }}
            bfren/apache:${{ steps.version.outputs.contents }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
