name: publish-2_4_4x

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-alpine2_4_4x:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Get repository name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash
      -
        name: Read image version
        uses: bfren/read-file@v1
        with:
          file: ./VERSION_MAJOR
        id: version_major
      -
        name: Read image version
        uses: bfren/read-file@v1
        with:
          file: ./VERSION_MINOR
        id: version_minor
      -
        name: Read image version
        uses: bfren/read-file@v1
        with:
          file: ./VERSION
        id: version
      -
        name: Read Apache version - revision
        uses: bfren/read-file@v1
        with:
          file: ./2.4.4x/APACHE_REVISION
        id: apache_revision
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./2.4.4x/Dockerfile
          build-args: |
            BF_IMAGE=${{ env.REPOSITORY_NAME }}
            BF_VERSION=${{ steps.version.outputs.contents }}
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bfren/apache:apache2.4.4x
            bfren/apache:apache2.4.4x-${{ steps.version_major.outputs.contents }}
            bfren/apache:apache2.4.4x-${{ steps.version_minor.outputs.contents }}
            bfren/apache:apache2.4.4x-${{ steps.version.outputs.contents }}
            bfren/apache:apache${{ steps.apache_revision.outputs.contents }}
            bfren/apache:apache${{ steps.apache_revision.outputs.contents }}-${{ steps.version.outputs.contents }}
            ghcr.io/bfren/apache:apache2.4.4x
            ghcr.io/bfren/apache:apache2.4.4x-${{ steps.version_major.outputs.contents }}
            ghcr.io/bfren/apache:apache2.4.4x-${{ steps.version_minor.outputs.contents }}
            ghcr.io/bfren/apache:apache2.4.4x-${{ steps.version.outputs.contents }}
            ghcr.io/bfren/apache:apache${{ steps.apache_revision.outputs.contents }}
            ghcr.io/bfren/apache:apache${{ steps.apache_revision.outputs.contents }}-${{ steps.version.outputs.contents }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
